---
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Using uv installer to speed up the build
# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
build:
    os: ubuntu-22.04
    tools:
        python: '3.11'
    jobs:
        pre_create_environment:
            - asdf plugin add uv
            - asdf install uv 0.5.17
            - asdf global uv 0.5.17
        create_environment:
            - uv venv $READTHEDOCS_VIRTUALENV_PATH
        install:
            - uv pip install .[docs] --no-cache --prefix $READTHEDOCS_VIRTUALENV_PATH

sphinx:
    builder: html
    fail_on_warning: true
    configuration: docs/source/conf.py
