---
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

python:
    install:
        - method: uv
          command: pip
          path: .
          extras:
              - docs

sphinx:
    builder: html
    fail_on_warning: true
    configuration: docs/source/conf.py
