[build-system]
requires = [
    "setuptools>=42,<84.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    # We can remove this once aiida-core drops dependency on pytz
    # https://github.com/aiidateam/aiida-core/issues/7544
    "ignore:datetime.datetime.:DeprecationWarning:pytz",
    # This one is coming from plumpy
    "ignore:There is no current event loop:DeprecationWarning:",
    # This is needed since SQLAlchemy 2.0, see
    # https://github.com/aiidalab/aiidalab-widgets-base/issues/605
    'ignore:Object of type.*not in session,.*operation along.*will not proceed:sqlalchemy.exc.SAWarning',
    'ignore:Creating AiiDA configuration:UserWarning:aiida',
    "ignore:crystal system 'cubic' is not interpreted for space group:UserWarning:ase.io.cif",
    # This popped up in spglib 2.5. Since we still try to support spglib v1,
    # it's not clear if we can get rid of it.
    "ignore:dict interface is deprecated. Use attribute interface instead:DeprecationWarning:spglib|aiidalab_widgets_base",
    "ignore:Set OLD_ERROR_HANDLING to false and catch the errors directly:DeprecationWarning:spglib",
    "ignore:Setting the shape on a NumPy array has been deprecated in NumPy 2.5:DeprecationWarning:ase"
]

[tool.ruff]
line-length = 88
show-fixes = true
target-version = "py39"

[tool.ruff.lint]
ignore = ["RUF012"]

# Temporarily disable ty type checking on these files
[[tool.ty.overrides]]
include = [
  "aiidalab_widgets_base/viewers.py",
  "aiidalab_widgets_base/structures.py",
]

[tool.ty.overrides.rules]
not-subscriptable = "ignore"
invalid-assignment = "ignore"
unresolved-attribute = "ignore"
invalid-argument-type = "ignore"
